// AUTO-GENERATED by app/scripts/gen-timestamps.cjs from metadata/whisper/*.json
// and content/tin-dung-la-gi.json. Do not edit by hand — re-run the script after
// regenerating narration audio.
export type Word = { text: string; startFrame: number; endFrame: number };
export type Phrase = { text: string; startFrame: number; endFrame: number };
export type NarrationTiming = {
  words: Word[];
  phrases: Phrase[];
  /** Frame at which the last recognized word ends (whisper-timed). Use for content pacing decisions. */
  speechEndFrame: number;
  /** Frame at which the actual audio FILE ends (ffprobe-measured). Use to cap <Sequence durationInFrames> for <Audio>. */
  mediaDurationFrames: number;
  /** @deprecated identical to speechEndFrame — kept for older call sites. */
  audioDurationFrames: number;
};

export const NARRATION: Record<string, NarrationTiming> = {
  "card_0a": {
    "words": [
      {
        "text": "Bạn",
        "startFrame": 11,
        "endFrame": 17
      },
      {
        "text": "đã",
        "startFrame": 17,
        "endFrame": 22
      },
      {
        "text": "bao",
        "startFrame": 24,
        "endFrame": 27
      },
      {
        "text": "giờ",
        "startFrame": 27,
        "endFrame": 34
      },
      {
        "text": "mua",
        "startFrame": 34,
        "endFrame": 38
      },
      {
        "text": "trước,",
        "startFrame": 38,
        "endFrame": 51
      },
      {
        "text": "trả",
        "startFrame": 54,
        "endFrame": 59
      },
      {
        "text": "sau",
        "startFrame": 59,
        "endFrame": 63
      },
      {
        "text": "trên",
        "startFrame": 63,
        "endFrame": 69
      },
      {
        "text": "sàn",
        "startFrame": 70,
        "endFrame": 76
      },
      {
        "text": "Cam",
        "startFrame": 78,
        "endFrame": 82
      },
      {
        "text": "hay",
        "startFrame": 82,
        "endFrame": 86
      },
      {
        "text": "chưa?",
        "startFrame": 86,
        "endFrame": 98
      },
      {
        "text": "Đó",
        "startFrame": 102,
        "endFrame": 105
      },
      {
        "text": "là",
        "startFrame": 105,
        "endFrame": 108
      },
      {
        "text": "một",
        "startFrame": 108,
        "endFrame": 115
      },
      {
        "text": "hình",
        "startFrame": 115,
        "endFrame": 121
      },
      {
        "text": "thức",
        "startFrame": 121,
        "endFrame": 128
      },
      {
        "text": "của",
        "startFrame": 128,
        "endFrame": 134
      },
      {
        "text": "tín",
        "startFrame": 134,
        "endFrame": 139
      },
      {
        "text": "dụng.",
        "startFrame": 139,
        "endFrame": 147
      }
    ],
    "phrases": [
      {
        "text": "Bạn đã bao giờ",
        "startFrame": 11,
        "endFrame": 34
      },
      {
        "text": "mua trước, trả sau",
        "startFrame": 34,
        "endFrame": 63
      },
      {
        "text": "trên sàn Cam hay",
        "startFrame": 63,
        "endFrame": 86
      },
      {
        "text": "chưa? Đó là một",
        "startFrame": 86,
        "endFrame": 115
      },
      {
        "text": "hình thức của tín",
        "startFrame": 115,
        "endFrame": 139
      },
      {
        "text": "dụng.",
        "startFrame": 139,
        "endFrame": 147
      }
    ],
    "speechEndFrame": 147,
    "mediaDurationFrames": 148,
    "audioDurationFrames": 147
  },
  "card_0b": {
    "words": [
      {
        "text": "Vậy,",
        "startFrame": 12,
        "endFrame": 21
      },
      {
        "text": "tín",
        "startFrame": 28,
        "endFrame": 37
      },
      {
        "text": "dụng",
        "startFrame": 37,
        "endFrame": 50
      },
      {
        "text": "là",
        "startFrame": 50,
        "endFrame": 52
      },
      {
        "text": "gì?",
        "startFrame": 57,
        "endFrame": 57
      }
    ],
    "phrases": [
      {
        "text": "Vậy, tín dụng là",
        "startFrame": 12,
        "endFrame": 52
      },
      {
        "text": "gì?",
        "startFrame": 57,
        "endFrame": 57
      }
    ],
    "speechEndFrame": 57,
    "mediaDurationFrames": 57,
    "audioDurationFrames": 57
  },
  "card_1": {
    "words": [
      {
        "text": "Bạn",
        "startFrame": 12,
        "endFrame": 18
      },
      {
        "text": "vay",
        "startFrame": 20,
        "endFrame": 22
      },
      {
        "text": "tiền",
        "startFrame": 22,
        "endFrame": 31
      },
      {
        "text": "mua",
        "startFrame": 31,
        "endFrame": 36
      },
      {
        "text": "nhà,",
        "startFrame": 36,
        "endFrame": 45
      },
      {
        "text": "quẹt",
        "startFrame": 45,
        "endFrame": 54
      },
      {
        "text": "thẻ",
        "startFrame": 54,
        "endFrame": 61
      },
      {
        "text": "mua",
        "startFrame": 61,
        "endFrame": 66
      },
      {
        "text": "đồ,",
        "startFrame": 66,
        "endFrame": 75
      },
      {
        "text": "hay",
        "startFrame": 75,
        "endFrame": 78
      },
      {
        "text": "mua",
        "startFrame": 82,
        "endFrame": 84
      },
      {
        "text": "trả",
        "startFrame": 86,
        "endFrame": 91
      },
      {
        "text": "góp",
        "startFrame": 91,
        "endFrame": 97
      },
      {
        "text": "một",
        "startFrame": 98,
        "endFrame": 103
      },
      {
        "text": "chiếc",
        "startFrame": 103,
        "endFrame": 111
      },
      {
        "text": "điện",
        "startFrame": 113,
        "endFrame": 123
      },
      {
        "text": "thoại.",
        "startFrame": 123,
        "endFrame": 135
      },
      {
        "text": "Tất",
        "startFrame": 136,
        "endFrame": 138
      },
      {
        "text": "cả",
        "startFrame": 141,
        "endFrame": 141
      },
      {
        "text": "đều",
        "startFrame": 142,
        "endFrame": 146
      },
      {
        "text": "có",
        "startFrame": 146,
        "endFrame": 148
      },
      {
        "text": "một",
        "startFrame": 148,
        "endFrame": 152
      },
      {
        "text": "điểm",
        "startFrame": 152,
        "endFrame": 158
      },
      {
        "text": "chung:",
        "startFrame": 160,
        "endFrame": 182
      },
      {
        "text": "bạn",
        "startFrame": 183,
        "endFrame": 188
      },
      {
        "text": "đang",
        "startFrame": 188,
        "endFrame": 193
      },
      {
        "text": "dùng",
        "startFrame": 193,
        "endFrame": 199
      },
      {
        "text": "tiền",
        "startFrame": 199,
        "endFrame": 205
      },
      {
        "text": "của",
        "startFrame": 205,
        "endFrame": 210
      },
      {
        "text": "người",
        "startFrame": 214,
        "endFrame": 218
      },
      {
        "text": "khác,",
        "startFrame": 221,
        "endFrame": 224
      },
      {
        "text": "để",
        "startFrame": 226,
        "endFrame": 230
      },
      {
        "text": "trả",
        "startFrame": 234,
        "endFrame": 237
      },
      {
        "text": "sau.",
        "startFrame": 237,
        "endFrame": 242
      }
    ],
    "phrases": [
      {
        "text": "Bạn vay tiền mua",
        "startFrame": 12,
        "endFrame": 36
      },
      {
        "text": "nhà, quẹt thẻ mua",
        "startFrame": 36,
        "endFrame": 66
      },
      {
        "text": "đồ, hay mua trả",
        "startFrame": 66,
        "endFrame": 91
      },
      {
        "text": "góp một chiếc điện",
        "startFrame": 91,
        "endFrame": 123
      },
      {
        "text": "thoại. Tất cả đều",
        "startFrame": 123,
        "endFrame": 146
      },
      {
        "text": "có một điểm chung:",
        "startFrame": 146,
        "endFrame": 182
      },
      {
        "text": "bạn đang dùng tiền",
        "startFrame": 183,
        "endFrame": 205
      },
      {
        "text": "của người khác, để",
        "startFrame": 205,
        "endFrame": 230
      },
      {
        "text": "trả sau.",
        "startFrame": 234,
        "endFrame": 242
      }
    ],
    "speechEndFrame": 242,
    "mediaDurationFrames": 248,
    "audioDurationFrames": 242
  },
  "card_2": {
    "words": [
      {
        "text": "Vậy",
        "startFrame": 12,
        "endFrame": 18
      },
      {
        "text": "thì,",
        "startFrame": 18,
        "endFrame": 24
      },
      {
        "text": "hiểu",
        "startFrame": 24,
        "endFrame": 30
      },
      {
        "text": "đơn",
        "startFrame": 36,
        "endFrame": 41
      },
      {
        "text": "giản,",
        "startFrame": 41,
        "endFrame": 51
      },
      {
        "text": "tín",
        "startFrame": 51,
        "endFrame": 57
      },
      {
        "text": "dụng",
        "startFrame": 57,
        "endFrame": 66
      },
      {
        "text": "là",
        "startFrame": 66,
        "endFrame": 70
      },
      {
        "text": "việc",
        "startFrame": 72,
        "endFrame": 80
      },
      {
        "text": "một",
        "startFrame": 82,
        "endFrame": 88
      },
      {
        "text": "bên,",
        "startFrame": 88,
        "endFrame": 100
      },
      {
        "text": "ngân",
        "startFrame": 103,
        "endFrame": 108
      },
      {
        "text": "hàng,",
        "startFrame": 108,
        "endFrame": 119
      },
      {
        "text": "tổ",
        "startFrame": 119,
        "endFrame": 126
      },
      {
        "text": "chức",
        "startFrame": 128,
        "endFrame": 135
      },
      {
        "text": "tài",
        "startFrame": 135,
        "endFrame": 141
      },
      {
        "text": "chính,",
        "startFrame": 141,
        "endFrame": 152
      },
      {
        "text": "hay",
        "startFrame": 159,
        "endFrame": 159
      },
      {
        "text": "người",
        "startFrame": 161,
        "endFrame": 175
      },
      {
        "text": "bán,",
        "startFrame": 175,
        "endFrame": 180
      },
      {
        "text": "cho",
        "startFrame": 187,
        "endFrame": 190
      },
      {
        "text": "bạn",
        "startFrame": 191,
        "endFrame": 196
      },
      {
        "text": "dùng",
        "startFrame": 196,
        "endFrame": 198
      },
      {
        "text": "một",
        "startFrame": 198,
        "endFrame": 204
      },
      {
        "text": "khoản",
        "startFrame": 207,
        "endFrame": 211
      },
      {
        "text": "tiền",
        "startFrame": 213,
        "endFrame": 218
      },
      {
        "text": "hoặc",
        "startFrame": 218,
        "endFrame": 223
      },
      {
        "text": "hàng",
        "startFrame": 223,
        "endFrame": 228
      },
      {
        "text": "hóa",
        "startFrame": 228,
        "endFrame": 233
      },
      {
        "text": "ngay",
        "startFrame": 233,
        "endFrame": 240
      },
      {
        "text": "bây",
        "startFrame": 240,
        "endFrame": 247
      },
      {
        "text": "giờ,",
        "startFrame": 247,
        "endFrame": 260
      },
      {
        "text": "rồi",
        "startFrame": 261,
        "endFrame": 267
      },
      {
        "text": "bạn",
        "startFrame": 267,
        "endFrame": 275
      },
      {
        "text": "trả",
        "startFrame": 275,
        "endFrame": 279
      },
      {
        "text": "lại",
        "startFrame": 284,
        "endFrame": 290
      },
      {
        "text": "sau,",
        "startFrame": 290,
        "endFrame": 291
      },
      {
        "text": "kèm",
        "startFrame": 296,
        "endFrame": 299
      },
      {
        "text": "một",
        "startFrame": 299,
        "endFrame": 306
      },
      {
        "text": "khoản",
        "startFrame": 309,
        "endFrame": 317
      },
      {
        "text": "lãi.",
        "startFrame": 317,
        "endFrame": 327
      }
    ],
    "phrases": [
      {
        "text": "Vậy thì, hiểu đơn",
        "startFrame": 12,
        "endFrame": 41
      },
      {
        "text": "giản, tín dụng là",
        "startFrame": 41,
        "endFrame": 70
      },
      {
        "text": "việc một bên, ngân",
        "startFrame": 72,
        "endFrame": 108
      },
      {
        "text": "hàng, tổ chức tài",
        "startFrame": 108,
        "endFrame": 141
      },
      {
        "text": "chính, hay người bán,",
        "startFrame": 141,
        "endFrame": 180
      },
      {
        "text": "cho bạn dùng một",
        "startFrame": 187,
        "endFrame": 204
      },
      {
        "text": "khoản tiền hoặc hàng",
        "startFrame": 207,
        "endFrame": 228
      },
      {
        "text": "hóa ngay bây giờ,",
        "startFrame": 228,
        "endFrame": 260
      },
      {
        "text": "rồi bạn trả lại",
        "startFrame": 261,
        "endFrame": 290
      },
      {
        "text": "sau, kèm một khoản",
        "startFrame": 290,
        "endFrame": 317
      },
      {
        "text": "lãi.",
        "startFrame": 317,
        "endFrame": 327
      }
    ],
    "speechEndFrame": 327,
    "mediaDurationFrames": 327,
    "audioDurationFrames": 327
  },
  "card_3": {
    "words": [
      {
        "text": "Hãy",
        "startFrame": 11,
        "endFrame": 15
      },
      {
        "text": "tưởng",
        "startFrame": 15,
        "endFrame": 24
      },
      {
        "text": "tượng",
        "startFrame": 25,
        "endFrame": 34
      },
      {
        "text": "tín",
        "startFrame": 34,
        "endFrame": 41
      },
      {
        "text": "dụng",
        "startFrame": 41,
        "endFrame": 48
      },
      {
        "text": "như",
        "startFrame": 51,
        "endFrame": 53
      },
      {
        "text": "một",
        "startFrame": 54,
        "endFrame": 59
      },
      {
        "text": "chiếc",
        "startFrame": 63,
        "endFrame": 68
      },
      {
        "text": "lò",
        "startFrame": 68,
        "endFrame": 71
      },
      {
        "text": "xo.",
        "startFrame": 71,
        "endFrame": 77
      },
      {
        "text": "Nó",
        "startFrame": 81,
        "endFrame": 81
      },
      {
        "text": "kéo",
        "startFrame": 81,
        "endFrame": 85
      },
      {
        "text": "dài",
        "startFrame": 85,
        "endFrame": 91
      },
      {
        "text": "sức",
        "startFrame": 92,
        "endFrame": 94
      },
      {
        "text": "mua",
        "startFrame": 97,
        "endFrame": 99
      },
      {
        "text": "của",
        "startFrame": 99,
        "endFrame": 105
      },
      {
        "text": "bạn",
        "startFrame": 105,
        "endFrame": 110
      },
      {
        "text": "ra",
        "startFrame": 110,
        "endFrame": 115
      },
      {
        "text": "trước",
        "startFrame": 118,
        "endFrame": 125
      },
      {
        "text": "thời",
        "startFrame": 125,
        "endFrame": 132
      },
      {
        "text": "gian",
        "startFrame": 132,
        "endFrame": 136
      },
      {
        "text": "thực",
        "startFrame": 136,
        "endFrame": 139
      },
      {
        "text": "tế",
        "startFrame": 143,
        "endFrame": 147
      },
      {
        "text": "bạn",
        "startFrame": 147,
        "endFrame": 152
      },
      {
        "text": "kiếm",
        "startFrame": 152,
        "endFrame": 158
      },
      {
        "text": "được",
        "startFrame": 158,
        "endFrame": 166
      },
      {
        "text": "tiền.",
        "startFrame": 166,
        "endFrame": 177
      },
      {
        "text": "Nhưng",
        "startFrame": 180,
        "endFrame": 187
      },
      {
        "text": "lò",
        "startFrame": 187,
        "endFrame": 190
      },
      {
        "text": "xo",
        "startFrame": 192,
        "endFrame": 194
      },
      {
        "text": "càng",
        "startFrame": 197,
        "endFrame": 204
      },
      {
        "text": "kéo",
        "startFrame": 204,
        "endFrame": 210
      },
      {
        "text": "dài,",
        "startFrame": 210,
        "endFrame": 223
      },
      {
        "text": "càng",
        "startFrame": 223,
        "endFrame": 226
      },
      {
        "text": "cần",
        "startFrame": 230,
        "endFrame": 236
      },
      {
        "text": "nhiều",
        "startFrame": 236,
        "endFrame": 245
      },
      {
        "text": "lực",
        "startFrame": 245,
        "endFrame": 252
      },
      {
        "text": "để",
        "startFrame": 252,
        "endFrame": 258
      },
      {
        "text": "kéo",
        "startFrame": 258,
        "endFrame": 263
      },
      {
        "text": "nó",
        "startFrame": 263,
        "endFrame": 267
      },
      {
        "text": "về",
        "startFrame": 267,
        "endFrame": 272
      },
      {
        "text": "đúng",
        "startFrame": 273,
        "endFrame": 280
      },
      {
        "text": "vị",
        "startFrame": 281,
        "endFrame": 286
      },
      {
        "text": "trí.",
        "startFrame": 286,
        "endFrame": 297
      }
    ],
    "phrases": [
      {
        "text": "Hãy tưởng tượng tín",
        "startFrame": 11,
        "endFrame": 41
      },
      {
        "text": "dụng như một chiếc",
        "startFrame": 41,
        "endFrame": 68
      },
      {
        "text": "lò xo. Nó kéo",
        "startFrame": 68,
        "endFrame": 85
      },
      {
        "text": "dài sức mua của",
        "startFrame": 85,
        "endFrame": 105
      },
      {
        "text": "bạn ra trước thời",
        "startFrame": 105,
        "endFrame": 132
      },
      {
        "text": "gian thực tế bạn",
        "startFrame": 132,
        "endFrame": 152
      },
      {
        "text": "kiếm được tiền. Nhưng",
        "startFrame": 152,
        "endFrame": 187
      },
      {
        "text": "lò xo càng kéo",
        "startFrame": 187,
        "endFrame": 210
      },
      {
        "text": "dài, càng cần nhiều",
        "startFrame": 210,
        "endFrame": 245
      },
      {
        "text": "lực để kéo nó",
        "startFrame": 245,
        "endFrame": 267
      },
      {
        "text": "về đúng vị trí.",
        "startFrame": 267,
        "endFrame": 297
      }
    ],
    "speechEndFrame": 297,
    "mediaDurationFrames": 294,
    "audioDurationFrames": 297
  },
  "card_3b": {
    "words": [
      {
        "text": "Nhưng",
        "startFrame": 14,
        "endFrame": 20
      },
      {
        "text": "nếu",
        "startFrame": 20,
        "endFrame": 28
      },
      {
        "text": "lò",
        "startFrame": 31,
        "endFrame": 32
      },
      {
        "text": "xo",
        "startFrame": 32,
        "endFrame": 35
      },
      {
        "text": "bị",
        "startFrame": 35,
        "endFrame": 41
      },
      {
        "text": "kéo",
        "startFrame": 41,
        "endFrame": 48
      },
      {
        "text": "giãn",
        "startFrame": 48,
        "endFrame": 55
      },
      {
        "text": "quá",
        "startFrame": 55,
        "endFrame": 62
      },
      {
        "text": "lâu,",
        "startFrame": 62,
        "endFrame": 72
      },
      {
        "text": "không",
        "startFrame": 76,
        "endFrame": 80
      },
      {
        "text": "thể",
        "startFrame": 80,
        "endFrame": 87
      },
      {
        "text": "co",
        "startFrame": 87,
        "endFrame": 91
      },
      {
        "text": "lại",
        "startFrame": 91,
        "endFrame": 97
      },
      {
        "text": "về",
        "startFrame": 97,
        "endFrame": 102
      },
      {
        "text": "đúng",
        "startFrame": 102,
        "endFrame": 110
      },
      {
        "text": "vị",
        "startFrame": 110,
        "endFrame": 115
      },
      {
        "text": "trí",
        "startFrame": 115,
        "endFrame": 120
      },
      {
        "text": "nữa,",
        "startFrame": 120,
        "endFrame": 123
      },
      {
        "text": "thì",
        "startFrame": 132,
        "endFrame": 132
      },
      {
        "text": "nợ",
        "startFrame": 132,
        "endFrame": 137
      },
      {
        "text": "xấu",
        "startFrame": 137,
        "endFrame": 141
      },
      {
        "text": "sẽ",
        "startFrame": 144,
        "endFrame": 148
      },
      {
        "text": "xuất",
        "startFrame": 148,
        "endFrame": 156
      },
      {
        "text": "hiện.",
        "startFrame": 156,
        "endFrame": 165
      }
    ],
    "phrases": [
      {
        "text": "Nhưng nếu lò xo",
        "startFrame": 14,
        "endFrame": 35
      },
      {
        "text": "bị kéo giãn quá",
        "startFrame": 35,
        "endFrame": 62
      },
      {
        "text": "lâu, không thể co",
        "startFrame": 62,
        "endFrame": 91
      },
      {
        "text": "lại về đúng vị",
        "startFrame": 91,
        "endFrame": 115
      },
      {
        "text": "trí nữa, thì nợ",
        "startFrame": 115,
        "endFrame": 137
      },
      {
        "text": "xấu sẽ xuất hiện.",
        "startFrame": 137,
        "endFrame": 165
      }
    ],
    "speechEndFrame": 165,
    "mediaDurationFrames": 171,
    "audioDurationFrames": 165
  },
  "card_4": {
    "words": [
      {
        "text": "Dùng",
        "startFrame": 11,
        "endFrame": 16
      },
      {
        "text": "đúng",
        "startFrame": 16,
        "endFrame": 24
      },
      {
        "text": "cách,",
        "startFrame": 24,
        "endFrame": 33
      },
      {
        "text": "tín",
        "startFrame": 35,
        "endFrame": 40
      },
      {
        "text": "dụng",
        "startFrame": 41,
        "endFrame": 48
      },
      {
        "text": "giúp",
        "startFrame": 48,
        "endFrame": 53
      },
      {
        "text": "bạn",
        "startFrame": 55,
        "endFrame": 60
      },
      {
        "text": "xoay",
        "startFrame": 62,
        "endFrame": 64
      },
      {
        "text": "vòng",
        "startFrame": 64,
        "endFrame": 71
      },
      {
        "text": "vốn",
        "startFrame": 71,
        "endFrame": 77
      },
      {
        "text": "kịp",
        "startFrame": 77,
        "endFrame": 83
      },
      {
        "text": "lúc,",
        "startFrame": 83,
        "endFrame": 96
      },
      {
        "text": "mua",
        "startFrame": 98,
        "endFrame": 99
      },
      {
        "text": "thứ",
        "startFrame": 99,
        "endFrame": 106
      },
      {
        "text": "cần",
        "startFrame": 106,
        "endFrame": 113
      },
      {
        "text": "ngay",
        "startFrame": 113,
        "endFrame": 121
      },
      {
        "text": "hôm",
        "startFrame": 121,
        "endFrame": 128
      },
      {
        "text": "nay,",
        "startFrame": 128,
        "endFrame": 132
      },
      {
        "text": "và",
        "startFrame": 137,
        "endFrame": 137
      },
      {
        "text": "xây",
        "startFrame": 138,
        "endFrame": 142
      },
      {
        "text": "dựng",
        "startFrame": 142,
        "endFrame": 148
      },
      {
        "text": "lịch",
        "startFrame": 150,
        "endFrame": 157
      },
      {
        "text": "sử",
        "startFrame": 157,
        "endFrame": 162
      },
      {
        "text": "tài",
        "startFrame": 162,
        "endFrame": 164
      },
      {
        "text": "chính",
        "startFrame": 166,
        "endFrame": 174
      },
      {
        "text": "tốt.",
        "startFrame": 174,
        "endFrame": 183
      },
      {
        "text": "Bí",
        "startFrame": 190,
        "endFrame": 192
      },
      {
        "text": "quyết",
        "startFrame": 192,
        "endFrame": 203
      },
      {
        "text": "chỉ",
        "startFrame": 203,
        "endFrame": 206
      },
      {
        "text": "đơn",
        "startFrame": 212,
        "endFrame": 216
      },
      {
        "text": "giản:",
        "startFrame": 217,
        "endFrame": 228
      },
      {
        "text": "vay",
        "startFrame": 228,
        "endFrame": 233
      },
      {
        "text": "trong",
        "startFrame": 233,
        "endFrame": 240
      },
      {
        "text": "khả",
        "startFrame": 240,
        "endFrame": 249
      },
      {
        "text": "năng,",
        "startFrame": 250,
        "endFrame": 257
      },
      {
        "text": "và",
        "startFrame": 257,
        "endFrame": 261
      },
      {
        "text": "luôn",
        "startFrame": 261,
        "endFrame": 264
      },
      {
        "text": "trả",
        "startFrame": 272,
        "endFrame": 276
      },
      {
        "text": "đúng",
        "startFrame": 276,
        "endFrame": 285
      },
      {
        "text": "hạn.",
        "startFrame": 285,
        "endFrame": 294
      }
    ],
    "phrases": [
      {
        "text": "Dùng đúng cách, tín",
        "startFrame": 11,
        "endFrame": 40
      },
      {
        "text": "dụng giúp bạn xoay",
        "startFrame": 41,
        "endFrame": 64
      },
      {
        "text": "vòng vốn kịp lúc,",
        "startFrame": 64,
        "endFrame": 96
      },
      {
        "text": "mua thứ cần ngay",
        "startFrame": 98,
        "endFrame": 121
      },
      {
        "text": "hôm nay, và xây",
        "startFrame": 121,
        "endFrame": 142
      },
      {
        "text": "dựng lịch sử tài",
        "startFrame": 142,
        "endFrame": 164
      },
      {
        "text": "chính tốt. Bí quyết",
        "startFrame": 166,
        "endFrame": 203
      },
      {
        "text": "chỉ đơn giản: vay",
        "startFrame": 203,
        "endFrame": 233
      },
      {
        "text": "trong khả năng, và",
        "startFrame": 233,
        "endFrame": 261
      },
      {
        "text": "luôn trả đúng hạn.",
        "startFrame": 261,
        "endFrame": 294
      }
    ],
    "speechEndFrame": 294,
    "mediaDurationFrames": 297,
    "audioDurationFrames": 294
  },
  "card_5": {
    "words": [
      {
        "text": "Và",
        "startFrame": 14,
        "endFrame": 14
      },
      {
        "text": "tín",
        "startFrame": 15,
        "endFrame": 17
      },
      {
        "text": "dụng",
        "startFrame": 19,
        "endFrame": 26
      },
      {
        "text": "cũng",
        "startFrame": 26,
        "endFrame": 32
      },
      {
        "text": "không",
        "startFrame": 32,
        "endFrame": 38
      },
      {
        "text": "phải",
        "startFrame": 40,
        "endFrame": 47
      },
      {
        "text": "là",
        "startFrame": 47,
        "endFrame": 50
      },
      {
        "text": "chuyện",
        "startFrame": 50,
        "endFrame": 60
      },
      {
        "text": "xa",
        "startFrame": 60,
        "endFrame": 62
      },
      {
        "text": "lạ",
        "startFrame": 62,
        "endFrame": 67
      },
      {
        "text": "gì",
        "startFrame": 67,
        "endFrame": 71
      },
      {
        "text": "ngày",
        "startFrame": 71,
        "endFrame": 77
      },
      {
        "text": "nay.",
        "startFrame": 77,
        "endFrame": 86
      },
      {
        "text": "Chỉ",
        "startFrame": 88,
        "endFrame": 93
      },
      {
        "text": "vài",
        "startFrame": 93,
        "endFrame": 98
      },
      {
        "text": "năm",
        "startFrame": 98,
        "endFrame": 104
      },
      {
        "text": "trước,",
        "startFrame": 104,
        "endFrame": 121
      },
      {
        "text": "mới",
        "startFrame": 122,
        "endFrame": 134
      },
      {
        "text": "17%",
        "startFrame": 134,
        "endFrame": 152
      },
      {
        "text": "người",
        "startFrame": 154,
        "endFrame": 162
      },
      {
        "text": "Việt",
        "startFrame": 162,
        "endFrame": 168
      },
      {
        "text": "mua",
        "startFrame": 168,
        "endFrame": 171
      },
      {
        "text": "trước",
        "startFrame": 172,
        "endFrame": 180
      },
      {
        "text": "trả",
        "startFrame": 180,
        "endFrame": 185
      },
      {
        "text": "sau,",
        "startFrame": 185,
        "endFrame": 192
      },
      {
        "text": "giờ",
        "startFrame": 195,
        "endFrame": 202
      },
      {
        "text": "đã",
        "startFrame": 202,
        "endFrame": 209
      },
      {
        "text": "gần",
        "startFrame": 209,
        "endFrame": 219
      },
      {
        "text": "49%",
        "startFrame": 219,
        "endFrame": 233
      },
      {
        "text": "còn",
        "startFrame": 233,
        "endFrame": 239
      },
      {
        "text": "thẻ",
        "startFrame": 239,
        "endFrame": 247
      },
      {
        "text": "tín",
        "startFrame": 247,
        "endFrame": 253
      },
      {
        "text": "dụng",
        "startFrame": 253,
        "endFrame": 260
      },
      {
        "text": "thì",
        "startFrame": 263,
        "endFrame": 273
      },
      {
        "text": "chiếm",
        "startFrame": 273,
        "endFrame": 276
      },
      {
        "text": "hơn",
        "startFrame": 276,
        "endFrame": 279
      },
      {
        "text": "nửa",
        "startFrame": 279,
        "endFrame": 282
      },
      {
        "text": "giá",
        "startFrame": 282,
        "endFrame": 287
      },
      {
        "text": "trị",
        "startFrame": 287,
        "endFrame": 293
      },
      {
        "text": "giao",
        "startFrame": 294,
        "endFrame": 298
      },
      {
        "text": "dịch",
        "startFrame": 298,
        "endFrame": 303
      },
      {
        "text": "thẻ",
        "startFrame": 306,
        "endFrame": 311
      },
      {
        "text": "cả",
        "startFrame": 313,
        "endFrame": 316
      },
      {
        "text": "nước.",
        "startFrame": 316,
        "endFrame": 328
      },
      {
        "text": "Nói",
        "startFrame": 329,
        "endFrame": 333
      },
      {
        "text": "cách",
        "startFrame": 333,
        "endFrame": 340
      },
      {
        "text": "khác,",
        "startFrame": 340,
        "endFrame": 349
      },
      {
        "text": "bạn",
        "startFrame": 349,
        "endFrame": 356
      },
      {
        "text": "có",
        "startFrame": 356,
        "endFrame": 360
      },
      {
        "text": "thể",
        "startFrame": 360,
        "endFrame": 365
      },
      {
        "text": "đã",
        "startFrame": 368,
        "endFrame": 369
      },
      {
        "text": "dùng",
        "startFrame": 373,
        "endFrame": 378
      },
      {
        "text": "tín",
        "startFrame": 378,
        "endFrame": 383
      },
      {
        "text": "dụng,",
        "startFrame": 383,
        "endFrame": 394
      },
      {
        "text": "chỉ",
        "startFrame": 394,
        "endFrame": 400
      },
      {
        "text": "là",
        "startFrame": 400,
        "endFrame": 400
      },
      {
        "text": "không",
        "startFrame": 407,
        "endFrame": 412
      },
      {
        "text": "để",
        "startFrame": 413,
        "endFrame": 419
      },
      {
        "text": "ý",
        "startFrame": 419,
        "endFrame": 422
      },
      {
        "text": "đến",
        "startFrame": 422,
        "endFrame": 429
      },
      {
        "text": "nó.",
        "startFrame": 429,
        "endFrame": 441
      },
      {
        "text": "Vậy,",
        "startFrame": 441,
        "endFrame": 449
      },
      {
        "text": "bạn",
        "startFrame": 450,
        "endFrame": 453
      },
      {
        "text": "đã",
        "startFrame": 456,
        "endFrame": 461
      },
      {
        "text": "thật",
        "startFrame": 461,
        "endFrame": 468
      },
      {
        "text": "sự",
        "startFrame": 468,
        "endFrame": 474
      },
      {
        "text": "biết",
        "startFrame": 474,
        "endFrame": 481
      },
      {
        "text": "tín",
        "startFrame": 481,
        "endFrame": 486
      },
      {
        "text": "dụng",
        "startFrame": 486,
        "endFrame": 493
      },
      {
        "text": "là",
        "startFrame": 497,
        "endFrame": 497
      },
      {
        "text": "gì",
        "startFrame": 497,
        "endFrame": 501
      },
      {
        "text": "chưa?",
        "startFrame": 501,
        "endFrame": 514
      }
    ],
    "phrases": [
      {
        "text": "Và tín dụng cũng",
        "startFrame": 14,
        "endFrame": 32
      },
      {
        "text": "không phải là chuyện",
        "startFrame": 32,
        "endFrame": 60
      },
      {
        "text": "xa lạ gì ngày",
        "startFrame": 60,
        "endFrame": 77
      },
      {
        "text": "nay. Chỉ vài năm",
        "startFrame": 77,
        "endFrame": 104
      },
      {
        "text": "trước, mới",
        "startFrame": 104,
        "endFrame": 134
      },
      {
        "text": "17% người Việt mua",
        "startFrame": 134,
        "endFrame": 171
      },
      {
        "text": "trước trả sau, giờ",
        "startFrame": 172,
        "endFrame": 202
      },
      {
        "text": "đã gần 49% còn",
        "startFrame": 202,
        "endFrame": 239
      },
      {
        "text": "thẻ tín dụng thì",
        "startFrame": 239,
        "endFrame": 273
      },
      {
        "text": "chiếm hơn nửa giá",
        "startFrame": 273,
        "endFrame": 287
      },
      {
        "text": "trị giao dịch thẻ",
        "startFrame": 287,
        "endFrame": 311
      },
      {
        "text": "cả nước. Nói cách",
        "startFrame": 313,
        "endFrame": 340
      },
      {
        "text": "khác, bạn có thể",
        "startFrame": 340,
        "endFrame": 365
      },
      {
        "text": "đã dùng tín dụng,",
        "startFrame": 368,
        "endFrame": 394
      },
      {
        "text": "chỉ là không để",
        "startFrame": 394,
        "endFrame": 419
      },
      {
        "text": "ý đến nó. Vậy,",
        "startFrame": 419,
        "endFrame": 449
      },
      {
        "text": "bạn đã thật sự",
        "startFrame": 450,
        "endFrame": 474
      },
      {
        "text": "biết tín dụng là",
        "startFrame": 474,
        "endFrame": 497
      },
      {
        "text": "gì chưa?",
        "startFrame": 497,
        "endFrame": 514
      }
    ],
    "speechEndFrame": 514,
    "mediaDurationFrames": 515,
    "audioDurationFrames": 514
  }
} as const;

/** First word in cardId whose text includes 'substring' (case-insensitive). Pass 'occurrence' (0-based) to pick a later match when the word repeats. */
export function findWord(cardId: string, substring: string, occurrence = 0): Word | undefined {
  const lower = substring.toLowerCase();
  const matches = NARRATION[cardId]?.words.filter((w) => w.text.toLowerCase().includes(lower)) ?? [];
  return matches[occurrence];
}

/** Same as findWord, but throws instead of silently returning undefined — use this for any cue whose absence would visibly break the card (an arrow with no target frame, a missing animation trigger), so a wording change surfaces as a build error instead of a silent no-op. */
export function requireWord(cardId: string, substring: string, occurrence = 0): Word {
  const word = findWord(cardId, substring, occurrence);
  if (!word) {
    throw new Error(`requireWord("${cardId}", "${substring}", ${occurrence}) found no match — did the script wording change? Check content/tin-dung-la-gi.json.`);
  }
  return word;
}
