import { Audio, Series, staticFile } from "remotion";
import { Card0aHook } from "./cards/Card0aHook";
import { Card0bTitle } from "./cards/Card0bTitle";
import { Card1Hook, CARD1_DURATION } from "./cards/Card1Hook";
import { Card3Metaphor, CARD3_DURATION } from "./cards/Card3Metaphor";
import { Card4Benefits } from "./cards/Card4Benefits";
import { Card5Stats } from "./cards/Card5Stats";

// v6: Card0 split into 0a (lead-in hook, new) + 0b (title, new design
// system). Card4 rewritten to benefits (was tín dụng vs nợ xấu comparison).
// Card5 rewritten with real data + closing question, doubling as the
// video's ending — Card6 (old separate conclusion) is dropped, its "tóm lại"
// role folded into Card5's closing line.
//
// Frame counts = real narration duration (metadata/whisper -> app/src/narrationTimestamps.ts,
// generated by scripts/generate_narration_v6.py + app/scripts/transcribe-one.mjs +
// app/scripts/gen-timestamps.cjs) + a short lead-in/tail hold per card.
// Durations tightened to (real audio length + a short visual hold), instead
// of the old generous padding that left multi-second dead air between cards
// (e.g. card1 was 350 vs 242 of audio = ~3.6s silence). This keeps the flow
// seamless — each card cuts shortly after its narration + settle.
export const CARD_DURATIONS = {
  card0a: 148, // full audio (137.52 frames) + 10-frame lead-in, without the extra tail hold
  card0b: 70, // shortened title hold for a quicker handoff to Card 1
  card1: CARD1_DURATION, // hook flows into definition with persistent person, bank and background
  card3: CARD3_DURATION, // continuous stretch + jam scene, with tightened narration join
  card4: 320, // audio 294
  card5: 556, // audio 514 + hold for closing question
} as const;

export const TOTAL_DURATION = Object.values(CARD_DURATIONS).reduce((a, b) => a + b, 0);

export const TinDungVideo: React.FC = () => (
  <>
    {/* Continuous ambient bed so the mix never drops to true silence between
        narration lines. No royalty-free upbeat music loop exists in
        metadata/sfx.json (only copyrighted "music_excerpt" entries, all
        correctly marked reference_only) — this is an ambience/drone texture
        standing in as a quiet room-tone, not proper music. Still an open
        item from the user. */}
    <Audio src={staticFile("sfx/ambient-pad.wav")} loop volume={0.1} />
    <Series>
      <Series.Sequence durationInFrames={CARD_DURATIONS.card0a}>
        <Card0aHook />
      </Series.Sequence>
      <Series.Sequence durationInFrames={CARD_DURATIONS.card0b}>
        <Card0bTitle />
      </Series.Sequence>
      <Series.Sequence durationInFrames={CARD_DURATIONS.card1}>
        <Card1Hook />
      </Series.Sequence>
      <Series.Sequence durationInFrames={CARD_DURATIONS.card3}>
        <Card3Metaphor />
      </Series.Sequence>
      <Series.Sequence durationInFrames={CARD_DURATIONS.card4}>
        <Card4Benefits />
      </Series.Sequence>
      <Series.Sequence durationInFrames={CARD_DURATIONS.card5}>
        <Card5Stats />
      </Series.Sequence>
    </Series>
  </>
);
