// Auto-generated by scripts/seo/update-helmets.mjs — DO NOT EDIT
// Edit scripts/seo/config.mjs instead and re-run: node scripts/seo/update-helmets.mjs

export interface PageMeta {
  title: string;
  description: string;
  url: string;
  ogImage: string;
}

export const PAGE_META: Record<string, PageMeta> = {
  '/': { title: 'Reicon — Open-Source Icon Library for Designers & Developers', description: 'Reicon — Free open-source SVG icons. 2,700+ handcrafted icons for React, Vue, Svelte, Flutter, Figma & more.', url: 'https://reicon.dev/', ogImage: 'https://reicon.dev/og/og-image.png' },
  '/icons': { title: 'Free Open-Source SVG Icons — Reicon', description: 'Browse 2,700+ free, open-source SVG icons in Outline and Filled weights. MIT licensed.', url: 'https://reicon.dev/icons', ogImage: 'https://reicon.dev/og/icons.jpeg' },
  '/docs': { title: 'Reicon Docs — Get Started', description: 'Get started with Reicon. Install and use icons in React, Vue, Svelte, Flutter, Figma, VS Code, and MCP.', url: 'https://reicon.dev/docs', ogImage: 'https://reicon.dev/og/docs.jpg' },
  '/docs/react': { title: 'Reicon for React — Reicon', description: 'Install and use Reicon in React. Import components, customize props, tree-shake unused icons.', url: 'https://reicon.dev/docs/react', ogImage: 'https://reicon.dev/og/docs-react.jpg' },
  '/docs/react-native': { title: 'Reicon for React Native — Reicon', description: 'Install and use Reicon in React Native. SVG components for Expo and bare React Native.', url: 'https://reicon.dev/docs/react-native', ogImage: 'https://reicon.dev/og/docs-react-native.jpg' },
  '/docs/vue': { title: 'Reicon for Vue — Reicon', description: 'Install and use Reicon in Vue 3 and Nuxt 3. Import components and customize props.', url: 'https://reicon.dev/docs/vue', ogImage: 'https://reicon.dev/og/docs-vue.jpg' },
  '/docs/svelte': { title: 'Reicon for Svelte — Reicon', description: 'Install and use Reicon in Svelte and SvelteKit. Import components and customize props.', url: 'https://reicon.dev/docs/svelte', ogImage: 'https://reicon.dev/og/docs-svelte.jpg' },
  '/docs/astro': { title: 'Reicon for Astro — Reicon', description: 'Install and use Reicon in Astro projects. Import Astro components, customize props, tree-shake unused icons.', url: 'https://reicon.dev/docs/astro', ogImage: 'https://reicon.dev/og/astro.png' },
  '/docs/vanilla': { title: 'Reicon for Vanilla JS — Reicon', description: 'Use Reicon icons via CDN in vanilla JavaScript and HTML. No build tools needed.', url: 'https://reicon.dev/docs/vanilla', ogImage: 'https://reicon.dev/og/docs-vanilla.jpg' },
  '/docs/figma': { title: 'Reicon for Figma — Reicon', description: 'Install the Reicon Figma plugin. Search, customize, and drag-and-drop icons onto your canvas.', url: 'https://reicon.dev/docs/figma', ogImage: 'https://reicon.dev/og/docs-figma.jpg' },
  '/docs/vscode': { title: 'Reicon for VS Code — Reicon', description: 'Install the Reicon VS Code extension. Search and insert icon code directly at your cursor.', url: 'https://reicon.dev/docs/vscode', ogImage: 'https://reicon.dev/og/docs-vscode.jpg' },
  '/docs/mcp': { title: 'Reicon MCP Server & CLI — Reicon', description: 'Let AI agents search 2,700+ icons, preview SVGs, and generate code. Runs as MCP server or standalone CLI.', url: 'https://reicon.dev/docs/mcp', ogImage: 'https://reicon.dev/og/docs-mcp.jpg' },
  '/docs/svg': { title: 'Reicon Raw SVGs — Reicon', description: 'Download and use raw Reicon SVG icons in HTML, static layouts, or CMS templates.', url: 'https://reicon.dev/docs/svg', ogImage: 'https://reicon.dev/og/docs.jpg' },
  '/docs/flutter': { title: 'Reicon for Flutter — Reicon', description: 'Install and use Reicon in Flutter and Dart projects. 2,700+ icons as raw SVG path strings.', url: 'https://reicon.dev/docs/flutter', ogImage: 'https://reicon.dev/og/docs-flutter.jpg' },
  '/packages': { title: 'Reicon Packages — Reicon', description: 'Official Reicon packages for React, React Native, Vue, Svelte, Flutter, and JavaScript.', url: 'https://reicon.dev/packages', ogImage: 'https://reicon.dev/og/packages.jpg' },
  '/pack': { title: 'Reicon Pack Builder — Reicon', description: 'Select and export custom icon packs. Download as SVG, PNG, or WebP ZIP files.', url: 'https://reicon.dev/pack', ogImage: 'https://reicon.dev/og/pack.jpg' },
  '/faq': { title: 'Reicon FAQ — Reicon', description: 'Answers about Reicon: license, framework support, Figma integration, and contributions.', url: 'https://reicon.dev/faq', ogImage: 'https://reicon.dev/og/faq.jpg' },
  '/support': { title: 'Sponsor Reicon — Dodo Payments', description: 'Sponsor ongoing open-source development of Reicon via Dodo Payments. Keep 2,700+ handcrafted SVG icons free for everyone.', url: 'https://reicon.dev/support', ogImage: 'https://reicon.dev/og/support.jpg' },
  '/terms': { title: 'Reicon Terms of Service — Reicon', description: 'Terms of service for using the Reicon open-source icon library.', url: 'https://reicon.dev/terms', ogImage: 'https://reicon.dev/og/terms.jpg' },
  '/privacy': { title: 'Reicon Privacy Policy — Reicon', description: 'Privacy policy for Reicon. Learn how we handle your data.', url: 'https://reicon.dev/privacy', ogImage: 'https://reicon.dev/og/privacy.jpg' },
  '/license': { title: 'Reicon MIT License — Reicon', description: 'Reicon is free and open-source under the MIT license. Use in personal and commercial projects.', url: 'https://reicon.dev/license', ogImage: 'https://reicon.dev/og/license.jpg' },
};

/** Framework-specific docs meta (keyed by framework ID, e.g. "react", "flutter") */
export const FRAMEWORK_META: Record<string, PageMeta> = {
  'react': { title: 'Reicon for React — Reicon', description: 'Install and use Reicon in React. Import components, customize props, tree-shake unused icons.', url: 'https://reicon.dev/docs/react', ogImage: 'https://reicon.dev/og/docs-react.jpg' },
  'react-native': { title: 'Reicon for React Native — Reicon', description: 'Install and use Reicon in React Native. SVG components for Expo and bare React Native.', url: 'https://reicon.dev/docs/react-native', ogImage: 'https://reicon.dev/og/docs-react-native.jpg' },
  'vue': { title: 'Reicon for Vue — Reicon', description: 'Install and use Reicon in Vue 3 and Nuxt 3. Import components and customize props.', url: 'https://reicon.dev/docs/vue', ogImage: 'https://reicon.dev/og/docs-vue.jpg' },
  'svelte': { title: 'Reicon for Svelte — Reicon', description: 'Install and use Reicon in Svelte and SvelteKit. Import components and customize props.', url: 'https://reicon.dev/docs/svelte', ogImage: 'https://reicon.dev/og/docs-svelte.jpg' },
  'astro': { title: 'Reicon for Astro — Reicon', description: 'Install and use Reicon in Astro projects. Import Astro components, customize props, tree-shake unused icons.', url: 'https://reicon.dev/docs/astro', ogImage: 'https://reicon.dev/og/astro.png' },
  'vanilla': { title: 'Reicon for Vanilla JS — Reicon', description: 'Use Reicon icons via CDN in vanilla JavaScript and HTML. No build tools needed.', url: 'https://reicon.dev/docs/vanilla', ogImage: 'https://reicon.dev/og/docs-vanilla.jpg' },
  'figma': { title: 'Reicon for Figma — Reicon', description: 'Install the Reicon Figma plugin. Search, customize, and drag-and-drop icons onto your canvas.', url: 'https://reicon.dev/docs/figma', ogImage: 'https://reicon.dev/og/docs-figma.jpg' },
  'vscode': { title: 'Reicon for VS Code — Reicon', description: 'Install the Reicon VS Code extension. Search and insert icon code directly at your cursor.', url: 'https://reicon.dev/docs/vscode', ogImage: 'https://reicon.dev/og/docs-vscode.jpg' },
  'mcp': { title: 'Reicon MCP Server & CLI — Reicon', description: 'Let AI agents search 2,700+ icons, preview SVGs, and generate code. Runs as MCP server or standalone CLI.', url: 'https://reicon.dev/docs/mcp', ogImage: 'https://reicon.dev/og/docs-mcp.jpg' },
  'svg': { title: 'Reicon Raw SVGs — Reicon', description: 'Download and use raw Reicon SVG icons in HTML, static layouts, or CMS templates.', url: 'https://reicon.dev/docs/svg', ogImage: 'https://reicon.dev/og/docs.jpg' },
  'flutter': { title: 'Reicon for Flutter — Reicon', description: 'Install and use Reicon in Flutter and Dart projects. 2,700+ icons as raw SVG path strings.', url: 'https://reicon.dev/docs/flutter', ogImage: 'https://reicon.dev/og/docs-flutter.jpg' },
};
