#!/usr/bin/env node

/**
 * update-helmets.mjs — Generates src/data/page-meta.ts from scripts/seo/config.mjs
 * so that React Helmet components always stay in sync with the route config.
 *
 * Run: node scripts/seo/update-helmets.mjs (after editing config.mjs)
 */

import { writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const SRC = resolve(__dirname, '../../src');

const { ROUTES, SITE } = await import('./config.mjs');

function esc(s) {
  return String(s).replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$/g, '\\$');
}

const routeEntries = ROUTES.map((r) => {
  const path = r.path;
  const url = path === '/' ? `${SITE}/` : `${SITE}${path}`;
  return `  '${path}': { title: '${esc(r.title)}', description: '${esc(r.description)}', url: '${esc(url)}', ogImage: '${esc(r.ogImage)}' },`;
}).join('\n');

// Framework docs alias map
const frameworkPairs = [
  ['react', 'docs/react'],
  ['react-native', 'docs/react-native'],
  ['vue', 'docs/vue'],
  ['svelte', 'docs/svelte'],
  ['astro', 'docs/astro'],
  ['vanilla', 'docs/vanilla'],
  ['figma', 'docs/figma'],
  ['vscode', 'docs/vscode'],
  ['mcp', 'docs/mcp'],
  ['svg', 'docs/svg'],
  ['flutter', 'docs/flutter'],
];
const frameworkEntries = frameworkPairs.map(([fw, routePath]) => {
  const r = ROUTES.find((x) => x.path === `/${routePath}`);
  if (!r) return '';
  return `  '${fw}': { title: '${esc(r.title)}', description: '${esc(r.description)}', url: '${SITE}/${routePath}', ogImage: '${esc(r.ogImage)}' },`;
}).filter(Boolean).join('\n');

const content = `// Auto-generated by scripts/seo/update-helmets.mjs — DO NOT EDIT
// Edit scripts/seo/config.mjs instead and re-run: node scripts/seo/update-helmets.mjs

export interface PageMeta {
  title: string;
  description: string;
  url: string;
  ogImage: string;
}

export const PAGE_META: Record<string, PageMeta> = {
${routeEntries}
};

/** Framework-specific docs meta (keyed by framework ID, e.g. "react", "flutter") */
export const FRAMEWORK_META: Record<string, PageMeta> = {
${frameworkEntries}
};
`;

const outPath = resolve(SRC, 'data/page-meta.ts');
const fwCount = frameworkPairs.length;
writeFileSync(outPath, content, 'utf-8');
console.log(`✓ Generated ${outPath} (${ROUTES.length} routes + ${fwCount} frameworks)`);
