// One-off generator: inlines characters/reicon/*.svg into app/src/icons.ts as string
// constants, so components can render them with dangerouslySetInnerHTML + CSS
// `color` (the source SVGs use fill="currentColor"). Re-run after adding new icons.
const fs = require("fs");
const path = require("path");

const SRC = path.join(__dirname, "..", "..", "characters", "reicon");
const OUT = path.join(__dirname, "..", "src", "icons.ts");

const files = fs.readdirSync(SRC).filter((f) => f.endsWith(".svg"));
const entries = files.map((f) => {
  const name = f.replace(/\.svg$/, "");
  const key = name.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());
  const svg = fs.readFileSync(path.join(SRC, f), "utf8").trim();
  return `  ${key}: \`${svg.replace(/`/g, "\\`")}\`,`;
});

const content = `// AUTO-GENERATED by app/scripts/gen-icons.cjs from characters/reicon/*.svg. Do not edit by hand.\nexport const ICONS = {\n${entries.join("\n")}\n} as const;\n\nexport type IconName = keyof typeof ICONS;\n`;

fs.writeFileSync(OUT, content, "utf8");
console.log(`Wrote ${files.length} icons to ${OUT}`);
