// Converts a raw unDraw SVG (flat list of <path>/<circle>/<polygon>/<rect>/
// <ellipse> elements, no semantic <g> grouping — confirmed by inspecting
// several files in G:\Casso\casso-video\svg) into a React component whose
// elements each carry a data-layer attribute ("bg" near-white/gray
// background shapes, "body" skin tones + unDraw's dark clothing grays
// #2f2e41/#3f3d56, "accent" the illustration's highlight color recolored to
// the Casso brand palette). This is what makes per-layer GSAP staggered
// reveal possible on a real illustration.
//
// CRITICAL: elements are emitted in their ORIGINAL document order (paint
// order), NOT regrouped into three stacked <g> blocks. An earlier version
// regrouped by color, which silently reordered z-index: e.g. a green
// hood/helmet shape drawn BEFORE the pink face in the source got moved into
// the "accent" group and painted AFTER (on top of) the face, erasing it.
// data-layer is an inline tag only; GSAP selects by it regardless of DOM
// position, so animation still works while the stacking stays faithful.
const fs = require("fs");
const path = require("path");

const NEUTRAL_BG_HEXES = new Set(["#ffffff", "#fff", "#f2f2f2", "#e6e6e6", "#cacaca", "#f1f1f1"]);
const SKIN_HEXES = new Set(["#ffb8b8", "#a0616a", "#ffb9b9", "#a0616b", "#9e616a", "#fbbebe", "#ffb6b6", "#ffb7b7"]);
const DARK_BODY_HEXES = new Set(["#2f2e41", "#3f3d56", "#2f2e42"]);

function run(srcPath, componentName, brandHex) {
  const svgRaw = fs.readFileSync(srcPath, "utf8");
  const viewBoxMatch = svgRaw.match(/viewBox="([^"]+)"/);
  const viewBox = viewBoxMatch ? viewBoxMatch[1] : "0 0 800 600";

  // Strip <defs>...</defs> BEFORE matching shape elements — a <defs> block
  // holds resource definitions (clipPath/gradient helper <rect>s etc.), not
  // visible shapes. Without this, a clipPath's own full-canvas <rect> (used
  // only to define a clip region, never rendered directly) gets pulled out
  // as if it were a real shape and, once placed outside its <clipPath> in a
  // plain layer <g>, becomes an opaque rectangle that silently paints over
  // every layer beneath it — confirmed on a real Figma-exported illustration
  // (figma_card0_credit_card_woman.svg) whose <defs><clipPath> rect was
  // exactly this shape.
  const svg = svgRaw.replace(/<defs>[\s\S]*?<\/defs>/g, "");

  const elementRe = /<(path|circle|polygon|rect|ellipse)\b[^>]*?\/>/g;
  const elements = svg.match(elementRe) || [];

  const fillCounts = {};
  for (const el of elements) {
    const m = el.match(/fill="(#[0-9a-fA-F]{3,8})"/);
    if (m) fillCounts[m[1].toLowerCase()] = (fillCounts[m[1].toLowerCase()] || 0) + 1;
  }
  let accentHex = null;
  let accentCount = 0;
  for (const [hex, count] of Object.entries(fillCounts)) {
    if (NEUTRAL_BG_HEXES.has(hex) || SKIN_HEXES.has(hex) || DARK_BODY_HEXES.has(hex)) continue;
    if (count > accentCount) {
      accentHex = hex;
      accentCount = count;
    }
  }

  const counts = { bg: 0, body: 0, accent: 0 };
  // Tag each element in place, preserving document (paint) order.
  const tagged = elements.map((el) => {
    const m = el.match(/fill="(#[0-9a-fA-F]{3,8})"/);
    const hex = m ? m[1].toLowerCase() : null;
    let layer, out;
    if (hex && NEUTRAL_BG_HEXES.has(hex)) {
      layer = "bg";
      out = el;
    } else if (hex && accentHex && hex === accentHex) {
      layer = "accent";
      out = el.replace(/fill="#[0-9a-fA-F]{3,8}"/, `fill="${brandHex}"`);
    } else {
      layer = "body";
      out = el;
    }
    counts[layer]++;
    // Insert data-layer right after the tag name so GSAP can select it.
    return out.replace(/^<(\w+)/, `<$1 data-layer="${layer}"`);
  });

  const tsx = `// AUTO-GENERATED by app/scripts/process_undraw.cjs from ${path
    .relative(process.cwd(), srcPath)
    .replace(/\\/g, "/")}
// Source: unDraw illustration (G:/Casso/casso-video/svg). Each shape carries
// a data-layer tag (bg/body/accent, accent recolored to the Casso brand
// palette) for per-layer GSAP reveal — but shapes stay in ORIGINAL paint
// order so z-index (e.g. face over hood) is preserved.
export const ${componentName}: React.FC<{ width?: number; height?: number }> = ({ width = 420, height = 300 }) => (
  <svg viewBox="${viewBox}" width={width} height={height} xmlns="http://www.w3.org/2000/svg" dangerouslySetInnerHTML={{ __html: ${JSON.stringify(
    tagged.join("")
  )} }} />
);
`;

  return { tsx, stats: { total: elements.length, ...counts, accentHex } };
}

const [, , srcArg, outArg, nameArg, brandArg] = process.argv;
if (!srcArg || !outArg || !nameArg) {
  console.log("usage: node process_undraw.cjs <src.svg> <out.tsx> <ComponentName> [brandHex]");
  process.exit(1);
}
const { tsx, stats } = run(srcArg, nameArg, brandArg || "#00A85E");
fs.writeFileSync(outArg, tsx);
console.log("wrote", outArg, stats);
